### ISSUE TITLE
--avro-annotation does not add avro annotations at all

### ISSUE THREAD

**Issue by AlexanderHagenhoff** [clemensv/avrotize#6]
Hello,

thank you for the project.

I've noticed that the --avro-annotation flag does not actually add Avro annotations to the generated Java classes. Instead, it seems to configure the code generation to use SpecificRecord, which is not the expected behavior based on the flag's name.
See https://github.com/clemensv/avrotize/blob/319085396949fdccbc6b16b76ce4f4a55a83c536/avrotize/avrotojava.py

In contrast, the --jackson-annotations flag works as expected by adding Jackson annotations to the generated Java classes, which is exactly what one would anticipate.

I believe the --avro-annotation flag should behave similarly to the --jackson-annotations flag by adding the appropriate Avro annotations, such as @AvroName, @AvroNamespace, and @AvroDoc, directly to the generated classes and fields. Please note that these are just examples and not an exhaustive list of all Avro annotations that could be included.

Would it be possible to update the behavior of the --avro-annotation flag to align with this expectation, ensuring it covers the full range of applicable Avro annotations?

Thank you for considering this improvement!

Best regards,
Alex

**Comment by clemensv** [comment]
Sorry about the delay. That is a bug and should work. I will investigate.

**Comment by AlexanderHagenhoff** [comment]
Hello Clemens,

Thank you for your response and for taking the time to look into this issue. I am confident that you will find an appropriate solution, but should you need any support, I am more than willing to help.

Thank you once again for your work on this library – it's exactly what I needed!

Best regards,
Alex

**Comment by clemensv** [comment]
Hi Alexander,

I first thought that the feature did not work, but you are saying something else. The Apache Avro framework doesn't work with annotations in Java but with SpecificRecord. I am using "annotations" as the generic term for serialization-specific additional code across all languages. So this is "by design".

Clemens
